apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.preinstall.pod.name }}
  namespace: {{ .Values.serviceNamespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-delete-policy": hook-failed
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  restartPolicy: Never
  serviceAccountName: {{ .Values.preinstall.serviceAccount }}
  containers:
  - name: {{ .Values.preinstall.pod.name }}
    image: {{ .Values.preinstall.pod.image }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    args:
      - "--csr-name"
      - {{ .Values.csrName }}
      - "--tls-secret-name"
      - {{ .Values.tlsSecretName }}
      - {{ .Values.preinstall.createNewCSR }}
      - "--kritis-service-name"
      - {{ .Values.serviceName }}
      - "--kritis-service-name-deployments"
      - {{ .Values.serviceNameDeployments }}
    command: {{ .Values.preinstall.pod.command }}
